AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  session-check-service

  SAM Template for session check service
  
Parameters:
  ProjectName:
    Type: String
    Default: session-checker
  MongoDBConnectionString:
    Type: String
  Altruists:
    Type: String
  AccountPrivateKey:
    Type: String
  AccountPassphrase:
    Type: String
  # TODO: Change to string array
  RedisHosts:
    Type: CommaDelimitedList
  RedisPorts:
    Type: CommaDelimitedList
  DefaultSyncAllowance:
    Type: String
  DefaultDispatcherList:
    Type: CommaDelimitedList

Globals:
  Function:
    Timeout: 180

Resources:
  SetupSessionCheck:
    Type: AWS::Serverless::Function 
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: setup-session-check 
      Description: Perfoms the data gathering and control flow of session check
      CodeUri: app/
      Handler: dist/functions/setup-session-check/app.handler
      Runtime: nodejs12.x
      MemorySize: 500
      Environment:
        Variables:
          MONGODB_CONN_STR: !Ref MongoDBConnectionString
          ALTRUISTS: !Ref Altruists
          ACCOUNT_PRIVATE_KEY: !Ref AccountPrivateKey
          ACCOUNT_PASSPHRASE: !Ref AccountPassphrase
          REDIS_HOSTS: !Ref RedisHosts
          REDIS_PORTS: !Ref RedisPorts
          DEFAULT_SYNC_ALLOWANCE: !Ref DefaultSyncAllowance
          DEFAULT_DISPATCHER_LIST: !Ref DefaultDispatcherList
      Policies:
        - "AWSLambdaVPCAccessExecutionRole"

Outputs:
  GatherSessionInfo:
    Description: "Setup Session Check Lambda Function ARN"
    Value: !GetAtt SetupSessionCheck.Arn
